### ISSUE TITLE
Multiple GPU support?

### ISSUE THREAD

**Issue by james-vincent** [nextpyp/cet_pick#11]
We find we must set CUDA_VISIBLE_DEVICES in order to run without error. Setting this to more than one device however we get a file error:

FileNotFoundError: [Errno 2] No such file or directory: 'exp/simsiam2d3d/test_sample/model_20.pth'

Does MiloPYP support more then one GPU?

**Comment by huangqinwen** [comment]
sorry currently it doesn't support multi-gpu yet. but the code should be able to work with a single gpu.

**Comment by hamid13r** [comment]
related to this: we get an error when we do 
```bash
python [...]
```
or
```bash
export CUDA_VISIBLE_DEVICES=0,1,2,3; python [...]
```
and we can only run the code if we specify only 1 GPU:
```bash
export CUDA_VISIBLE_DEVICES=3; python [...]
```

**Comment by huangqinwen** [comment]
hi! can you elaborate on the error message? if it is single gpu it runs? sorry we haven't implemented multi-gpu yet for this.

**Comment by hamid13r** [comment]
if we don't explicitly set one GPU we get this error:
```bash
Traceback (most recent call last):
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/cuda/__init__.py", line 311, in _lazy_init
    queued_call()
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/cuda/__init__.py", line 180, in _check_capability
    capability = get_device_capability(d)
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/cuda/__init__.py", line 435, in get_device_capability
    prop = get_device_properties(device)
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/cuda/__init__.py", line 453, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/cet_pick/cet_pick/simsiam_main.py", line 170, in <module>
    main(opt)
  File "/scratch/cet_pick/cet_pick/simsiam_main.py", line 77, in main
    trainer.set_device(opt.gpus, opt.chunk_sizes, opt.device)
  File "/scratch/cet_pick/cet_pick/trains/base_trainer.py", line 245, in set_device
    self.model_with_loss = self.model_with_loss.to(device)
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/cuda/__init__.py", line 317, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=

CUDA call was originally invoked at:

  File "/scratch/cet_pick/cet_pick/simsiam_main.py", line 9, in <module>
    import torch
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/__init__.py", line 1332, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/cuda/__init__.py", line 244, in <module>
    _lazy_call(_check_capability)
  File "/scratch/micromamba/envs/MiLoPYP/lib/python3.8/site-packages/torch/cuda/__init__.py", line 241, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))
```

this happens if we run
```bash
python /scratch/cet_pick/cet_pick/simsiam_main.py simsiam3d --num_epochs 20 --exp_id NAD039_4_exp1 --bbox 36 --dataset simsiam3d --arch simsiam2d_18 --lr 1e-3 --train_img_txt training.txt --batch_size 256 --val_intervals 20 --save_all --gauss 0.8 --dog 3,5 --gpus 0
```
The only way it run is if we set ONE gpu explicitly:
```bash
export CUDA_VISIBLE_DEVICES=3;python /scratch/cet_pick/cet_pick/simsiam_main.py simsiam3d --num_epochs 20 --exp_id NAD039_4_exp1 --bbox 36 --dataset simsiam3d --arch simsiam2d_18 --lr 1e-3 --train_img_txt training.txt --batch_size 256 --val_intervals 20 --save_all --gauss 0.8 --dog 3,5 --gpus 0
```
