### ISSUE TITLE
3D interactive session using phoenix did not show any content

### ISSUE THREAD

**Issue by ZhenHuangLab** [nextpyp/cet_pick#7]
### Issue Type
bug

### MiLoPYP version
v0.5.0

### Description
When initiating the 3D interactive session **locally** in Cellular Content Exploration by running the code below:
```
python phoenix_visualization.py --input exp/simsiam2d3d/test_sample/interactive_info_parquet.gzip
```

![image](https://github.com/user-attachments/assets/889e3721-60f7-4a15-9b58-d25066a9e953)

The session was hosted successfully, and by opening the web address I could see the title `Phoenix` and its icon. But, it did not show any content and was always blank. I have waited for hours and tried refreshing or re-launching the phoenix but they didn't work.

![image](https://github.com/user-attachments/assets/5bf5ba36-13b0-43d3-a22f-3c012d75d0ef)

Do you have any suggestions?

### Additional Info
- I have followed the instructions in Quick tutorials for globular-shaped targets and the dataset is from `milopyp_globular_tutorial.tbz`. I just paused at `3D interactive session` section.
- The 2D visualization was successful. 
- The images generated by `plot_2d.py` are hosted in the background on port 7000 and they are accessible.

### GPU
Tesla V100-PCIE-16GB * 1

### CUDA version
cuda-11.7

### Software Setup
torch==1.13.0+cu117 torchaudio==0.13.0 torchvision==0.14.0+cu117
arize-phoenix 0.0.27, matplotlib 3.7.5, numpy 1.24.4, numba 0.58.1, scipy 1.10.1

**Comment by abartesaghi** [comment]
This seems to be an issue with the Phoenix app itself. Did you try clearing the cache or using a different browser? [Here](https://github.com/Arize-ai/phoenix/issues/2912) is a discussion on a similar issue that could be helpful.

**Comment by ZhenHuangLab** [comment]
I found that cleaning my browser cache didn't work, as mentioned in the similar issue you provided.

Then I tried setting up `nvm` and `pnpm` to build the phoenix app (using `node v16.20.2` and `npm v8.19.4` because `glibc` in centos7 doesn't support node 18 and higher, and it's kind of annoying to upgrade `glibc`), by following the instruction in [phoenix/app/readme](https://github.com/Arize-ai/phoenix/tree/main/app) and [phoenix/development](https://github.com/Arize-ai/phoenix/blob/336d9314916fb4cf01e1fe9410532a6d29cdbc5b/DEVELOPMENT.md):

```
$ nvm use 16
Now using node v16.20.2 (npm v8.19.4)

# now in phoenix/app/
$ pnpm install --frozen-lockfile
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 21.9s

$ pip show arize-phoenix
Name: arize-phoenix
Version: 5.6.0
Summary: AI Observability and Evaluation
Home-page:
Author:
Author-email: Arize AI <phoenix-devs@arize.com>
License: Elastic-2.0
Location: .../lab01/conda_env/envs/phoenix/lib/python3.9/site-packages
Editable project location: .../zhen/phoenix
Requires: aioitertools, aiosqlite, alembic, arize-phoenix-evals, arize-phoenix-otel, authlib, cachetools, fastapi, grpc-interceptor, grpcio, httpx, jinja2, numpy, openinference-instrumentation, openinference-semantic-conventions, opentelemetry-exporter-otlp, opentelemetry-proto, opentelemetry-sdk, opentelemetry-semantic-conventions, pandas, protobuf, psutil, pyarrow, pydantic, python-multipart, scikit-learn, scipy, sqlalchemy, sqlean-py, starlette, strawberry-graphql, tqdm, typing-extensions, uvicorn, websockets, wrapt
Required-by:

$ pnpm run build

> phoenix-ui@0.0.1 build .../zhen/phoenix/app
> pnpm run build:relay && vite build


> phoenix-ui@0.0.1 build:relay .../zhen/phoenix/app
> relay-compiler

[INFO] [default] compiling...
[INFO] [default] compiled documents: 139 reader, 104 normalization, 149 operation text
[INFO] Compilation completed.
[INFO] Done.
vite v5.4.10 building for production...
node_modules/.pnpm/three-stdlib@2.34.0_three@0.139.2/node_modules/three-stdlib/libs/lottie.js (13062:32): Use of eval in "node_modules/.pnpm/three-stdlib@2.34.0_three@0.139.2/node_modules/three-stdlib/libs/lottie.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/.pnpm/three-mesh-bvh@0.7.8_three@0.139.2/node_modules/three-mesh-bvh/src/utils/ExtensionUtilities.js (6:26): "BatchedMesh" is not exported by "node_modules/.pnpm/three@0.139.2/node_modules/three/build/three.module.js", imported by "node_modules/.pnpm/three-mesh-bvh@0.7.8_three@0.139.2/node_modules/three-mesh-bvh/src/utils/ExtensionUtilities.js".
✓ 4117 modules transformed.
../../src/phoenix/server/static/.vite/manifest.json                        1.93 kB │ gzip:     0.40 kB
../../src/phoenix/server/static/assets/vendor-Cg6lcjUC.css                 1.82 kB │ gzip:     0.77 kB
../../src/phoenix/server/static/assets/index-DqLgwdks.js                   7.16 kB │ gzip:     2.41 kB
../../src/phoenix/server/static/assets/vendor-recharts-DgwO5t0F.js       298.80 kB │ gzip:    67.10 kB
../../src/phoenix/server/static/assets/components-v7Tbuo8y.js            299.91 kB │ gzip:    82.30 kB
../../src/phoenix/server/static/assets/vendor-arizeai-D373FxfT.js        307.00 kB │ gzip:    84.67 kB
../../src/phoenix/server/static/assets/vendor-codemirror-B-gpTz_s.js     393.56 kB │ gzip:   127.20 kB
../../src/phoenix/server/static/assets/pages-DULbjTlg.js                 578.18 kB │ gzip:   114.82 kB
../../src/phoenix/server/static/assets/vendor-three-t78-ZqWt.js          620.97 kB │ gzip:   158.16 kB
../../src/phoenix/server/static/assets/vendor-AVwlOmm_.js             10,942.71 kB │ gzip: 2,224.72 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 55.40s
```

The phoenix app seemed to be successfully built. But, when I tried to run the command once again, it crashed again:

```
# Now in cet_pick/
$ python phoenix_visualization.py --input exp/simsiam2d3d/test_sample/interactive_info_parquet.gzip
Traceback (most recent call last):
  File ".../zhen/MiLoPYP/cet_pick/cet_pick/phoenix_visualization.py", line 2, in <module>
    import phoenix as px
  File ".../zhen/phoenix/src/phoenix/__init__.py", line 10, in <module>
    from .session.client import Client
  File ".../zhen/phoenix/src/phoenix/session/client.py", line 33, in <module>
    from phoenix.experiments.types import Dataset, Example, Experiment
  File ".../zhen/phoenix/src/phoenix/experiments/__init__.py", line 1, in <module>
    from .functions import evaluate_experiment, run_experiment
  File ".../zhen/phoenix/src/phoenix/experiments/functions.py", line 34, in <module>
    from phoenix.evals.executors import get_executor_on_sync_context
ModuleNotFoundError: No module named 'phoenix.evals'
```

Then I re-installed the arize-phoenix by `pip install arize-phoenix[evals]`, and revised the `phoenix_visualization.py` because in the latest arize-phoenix (v5.6.0) `px.Dataset` was renamed to `px.Inferences`:

```diff
# in phoenix_visualization.py
- train_ds = px.Dataset(dataframe=train_df, schema=train_schema)
+ train_ds = px.Inferences(dataframe=train_df, schema=train_schema)
```

It seemed that it finally worked. But I could not open `http://localhost:6006/`:

```
$ python phoenix_visualization.py --input exp/simsiam2d3d/test_sample/interactive_info_parquet.gzip &
[1] 28027
name            coord  ... label                             image
0  tilt1   [266, 97, 126]  ...    38  http://localhost:7000/imgs/0.png
1  tilt1   [355, 76, 134]  ...    32  http://localhost:7000/imgs/1.png
2  tilt1  [251, 249, 124]  ...    38  http://localhost:7000/imgs/2.png
3  tilt1  [281, 273, 133]  ...    38  http://localhost:7000/imgs/3.png
4  tilt1   [303, 94, 133]  ...    32  http://localhost:7000/imgs/4.png

[5 rows x 5 columns]
🌍 To view the Phoenix app in your browser, visit http://localhost:6006/
📖 For more information on how to use Phoenix, check out https://docs.arize.com/phoenix
```

Then I undid the revision in `phoenix_visualization.py`, and re-installed the `arize-phoenix==0.0.27`.

```
$ python phoenix_visualization.py --input exp/simsiam2d3d/test_sample/interactive_info_parquet.gzip
.../lab01/conda_env/envs/phoenix/lib/python3.9/site-packages/pydantic/_migration.py:290: UserWarning: `pydantic.utils:lenient_issubclass` has been removed. We are importing from `pydantic.v1.utils:lenient_issubclass` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
.../lab01/conda_env/envs/phoenix/lib/python3.9/site-packages/pydantic/_migration.py:290: UserWarning: `pydantic.utils:smart_deepcopy` has been removed. We are importing from `pydantic.v1.utils:smart_deepcopy` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/
  warnings.warn(
    name            coord  ... label                             image
0  tilt1   [266, 97, 126]  ...    38  http://localhost:7000/imgs/0.png
1  tilt1   [355, 76, 134]  ...    32  http://localhost:7000/imgs/1.png
2  tilt1  [251, 249, 124]  ...    38  http://localhost:7000/imgs/2.png
3  tilt1  [281, 273, 133]  ...    38  http://localhost:7000/imgs/3.png
4  tilt1   [303, 94, 133]  ...    32  http://localhost:7000/imgs/4.png

[5 rows x 5 columns]
🌍 To view the Phoenix app in your browser, visit http://localhost:39301/
📺 To view the Phoenix app in a notebook, run `px.active_session().view()`
📖 For more information on how to use Phoenix, check out https://docs.arize.com/phoenix
```

But, the dashboard was blank again. lol

So, next step, I will try **running docker on my mac**, to see if it works.

Have you ever tried `phoenix_visualization.py` on your remote machine/cluster (in documentation it seems that you run `3D interactive session` on personal laptop)? What would you suggest? Thank you!

### Additional info
System: CentOS Linux 7.5.1804
Required library versions: (for phoenix-visualization)

```
dataset==1.6.2
healpy==1.14.0
opencv_contrib_python==4.7.0.72
Pillow==10.0.0
numba==0.60.0
numpy==1.26.4
pandas==2.2.1
arize-phoenix==0.0.27
arize-phoenix-evals==0.17.2
arize-phoenix-otel==0.5.1
pyarrow==15.0.0
scipy==1.13.1
strawberry-graphql==0.178.0
sqlean.py==3.45.1
```

**Comment by ZhenHuangLab** [comment]
So Strange -- when I installed `arize-phoenix` on my mac using these commands below:

```
conda create --name milopyp python=3.8
conda activate milopyp
pip install pandas==2.0.3 arize-phoenix==0.0.27
/Users/zhenhuang/opt/anaconda3/envs/milopyp/bin/python /Users/zhenhuang/Documents/milopyp/phoenix_visualization.py --input exp/simsiam2d3d/test_sample/interactive_info_parquet.gzip
```

I got the expected output:
<img width="777" alt="image" src="https://github.com/user-attachments/assets/2bb1388f-3c67-4a2b-b8c1-d4ce52c21617">

And finally, I can see the dashboard in the browser, Hooray!
![image](https://github.com/user-attachments/assets/5ffb0974-fc28-43cc-97c0-5298c1f11942)

So, I think it should be highlighted in the documentation that it is better to run the entire `3D interactive session` on one's local machine like mac, but not on the cluster or the remote machine. It's kind of confusing because all the steps before `3D interactive session` could run on the remote machine.

And my questions remain:
> Have you ever tried `phoenix_visualization.py` on your remote machine/cluster (in documentation it seems that you run `3D interactive session` on personal laptop)? What would you suggest? Thank you!

It would be better if the `3D interactive session` could also run on the cluster, so that there is no need to copy the `interactive_info_parquet.gzip`, `exp/`,and `phoenix_visualization.py` to my mac and do this stuff locally.

**Comment by huangqinwen** [comment]
Thank you! We will look into this. Last time when I tried to run it on a remote cluster it worked fine but will retest!
