### ISSUE TITLE
MiLoPYP does not appear to be able to access https

### ISSUE THREAD

**Issue by abnerabner** [nextpyp/cet_pick#8]
Hi, I successfully installed MiLoPYP without any problem.
But when I ran the code in tutorial:

`python simsiam_main.py simsiam2d3d --num_epochs 20 --exp_id test_sample --bbox 36 --dataset simsiam2d3d --arch simsiam2d3d_18 --lr 1e-3 --train_img_txt sample_train_explore_img.txt --batch_size 256 --val_intervals 20 --save_all --gauss 0.8 --dog 3,5`

the following error occured

```
Creating model...
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/zhenglin/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
Traceback (most recent call last):
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/http/client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/ssl.py", line 1073, in _create
    self.do_handshake()
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1149)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simsiam_main.py", line 170, in <module>
    main(opt)
  File "simsiam_main.py", line 60, in main
    model = create_model(opt.arch, opt.heads, opt.head_conv)
  File "/data1/zhenglin/test/template_picking_test/milopyp/cet_pick-main/cet_pick/models/model.py", line 69, in create_model
    model = get_model(num_layers=num_layers, heads=heads, head_conv=head_conv,last_k = last_k)
  File "/data1/zhenglin/test/template_picking_test/milopyp/cet_pick-main/cet_pick/models/networks/simsiam_model_2d3d.py", line 855, in get_simsiam2d3d_net_small
    model.init_weights(num_layers)
  File "/data1/zhenglin/test/template_picking_test/milopyp/cet_pick-main/cet_pick/models/networks/simsiam_model_2d3d.py", line 800, in init_weights
    pretrained_state_dict = model_zoo.load_url(url)
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/site-packages/torch/hub.py", line 591, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/site-packages/torch/hub.py", line 457, in download_url_to_file
    u = urlopen(req)
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/zhenglin/.conda/envs/MiLoPYP/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1149)>
```

Do you have any suggestions?

Best,
Abner.

**Comment by huangqinwen** [comment]
seems to be a urllib3 version problem - can you try the solutions here: [upgrade/downgrade urllib](https://stackoverflow.com/questions/65516325/ssl-wrong-version-number-on-python-request )

**Comment by abnerabner** [comment]
> seems to be a urllib3 version problem - can you try the solutions here: [upgrade/downgrade urllib](https://stackoverflow.com/questions/65516325/ssl-wrong-version-number-on-python-request)

Thanks a lot! The problem has been solved. According to the link above, I checked my urllib and found that he was already at version 1.23, then I updated urllib3 but still got the same error, finally I had to change all https to http and finally it continued to run!
